### ISSUE TITLE
Error during all-season roads indicator assessment

### ISSUE THREAD

**Issue by JudaGarcia99** [miguel-capsus/UPT-Calculus-Modules#2]
While evaluating the all-season roads indicator the log console showed up this error message: 

![image](https://user-images.githubusercontent.com/63655568/79247554-4a6ebf00-7e40-11ea-8ca3-1be2241bce36.png)

Can you take a look, please?

**Comment by miguel-capsus** [comment]
The issue was fixed by installing the latest version of the calculus module.
